runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node