runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: 15
    - uses: actions/cache@v2.1.3
      with:
        path: node_modules
        key: ${{ runner.os }}-node